# This YAML file defines the CI/CD pipeline for building and testing the Docker image

# Define the stages of the pipeline
stages:
  - build
  - deploy

# Define the jobs for each stage
build:
  stage: build
  image: docker:stable

  variables:
    DOCKER_USER: priyanshiorufy
    DOCKER_PASSWORD: orufy@123

  services:
    - docker:dind

  script:
    - docker build -t wisecow-image .

deploy:
    image: mcr.microsoft.com/azure-cli
    stage: deploy
    script:
      - az login --tenant 12b4fbf9-dea8-4490-bede-9cc40309ad61 --use-device-code
      - az aks install-cli
      - az aks get-credentials --name AccuknoxTask --overwrite-existing --resource-group TASK
      - kubectl apply -f wisecow-deployment.yaml
      - kubectl apply -f wisecow-service.yaml
        

