# This YAML file defines the CI/CD pipeline for building and testing the Docker image

# Define the stages of the pipeline
stages:
  - build
  

# Define the jobs for each stage
build:
  stage: build
  image: docker:stable

  variables:
    DOCKER_USER: priyanshiorufy
    DOCKER_PASSWORD: orufy@123

  services:
    - docker:dind

  script:
    - docker build -t wisecow-image .

