# This YAML file defines the CI/CD pipeline for building and testing the Docker image

# Define the stages of the pipeline
stages:
  - build
  - deploy
  

# Define the jobs for each stage
build:
  stage: build
  image: docker:stable

  variables:
    DOCKER_USER: priyanshiorufy
    DOCKER_PASSWORD: orufy@123

  services:
    - docker:dind

  script:
    - docker build -t wisecow-app .


deploy:
  stage: deploy
  image: docker:stable

  script:
    # Install kubectl
    - apk add --no-cache curl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/

    # Apply Kubernetes manifest files
    - kubectl apply -f wisecow-deployment.yaml
    - kubectl apply -f wisecow-service.yaml

  only:
    - master
        

