# This YAML file defines the CI/CD pipeline for building and testing the Docker image

# Define the stages of the pipeline
stages:
  - build
  - deploy

# Define the jobs for each stage
build:
  stage: build
  image: docker:stable

  variables:
    DOCKER_USER: priyanshiorufy
    DOCKER_PASSWORD: orufy@123

  services:
    - docker:dind

  script:
    - docker build -t wisecow-image .

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    -az login -u $AZURE_EMAIL -p $AZURE_PASSWORD
    -az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $AKS_CLUSTER_NAME --overwrite-existing
    -kubectl apply -f wisecow-deployment.yaml
    -kubectl apply -f wisecow-service.yml

